[package]
name = "stock_market_monitor"
version = "0.1.0"
authors = ["jaysinh01 <jaysinh@ualberta.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
